### ISSUE TITLE
Oppgrader til jena5

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-dataset-harvester#195]
Vi sliter med å høste katalogen til geonorge med jena5, avventer oppgradering til vi hjelper de til å lage en jena5-vennlig versjon av katalogen

**Comment by terjesyl** [comment]
En endring i Jena 5 er at de har gått fra ARP til RRX for å parse RDF/XML.

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/pull/197
