### ISSUE TITLE
/ready bør bruke egna metod for readiness

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-dataset-harvester#37]
I dag bruker /ready metoden `catalogService.countDatasetCatalogs()`. Dermed rapporteres det status code != 200 dersom det er "dårlige" data i databasen. 

/ready bør bruke ei enklare metod. Kva med å bruke /$/ping, ref https://jena.apache.org/documentation/fuseki2/fuseki-server-protocol.html#server-information

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/issues/19
