### ISSUE TITLE
Gå vekk fra Fuseki som DB for Datasettharvester

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-dataset-harvester#58]
- [x] Opprette mongoDB i datasett-harvester og legger inn en slags ETL for Fuseki mot ny DB. 

- [x] Fjerne all nåværende bruk av fuseki fra Datasett harvester.

- [x] Legge til nytt fuseki-datasett i fdk-fuseki-service

- [x] Lagre full modell i fuseki, som cache til bruk for sparql.

- [x] Legge til sparql i nginx, som peker til fdk-fuseki-service

- [x] Endre sparql-spørringer i org-bff og report-bff til å gå mot ny sparql-nginx

- [x] Gå over til å bruke fdk-dataset-harvester i stedet for new-dataset-harvester i fulltext o.a.

- [x] Fjerne new-dataset-harvester og aktivere rabbit-publisher i fdk-dataset-harvester

**Comment by NilsOveTen** [comment]
@lillelars Å teste dette går mest på å sjekke at det ikke mangler noe på div datasett, det er data som ikke ligger på 'toppnivå' som står i fare for å forsvinne. Dvs kontaktinfo, distribusjoner o.l. kan potensielt ha mistet informasjon.

**Comment by lillelars** [comment]
Dette ser ut til å fungere som forventet. Håndterer relasjonsbug i eget issue. Testet i chrome.
